-- create tables

DROP TABLE IF EXISTS RECIPE;
CREATE TABLE RECIPE (
id INT AUTO_INCREMENT PRIMARY KEY,
course_id INT,
food_category_id INT,
recipe_name VARCHAR(255),
recipe_description TEXT NOT NULL,
prep_time TIME
);

DROP TABLE IF EXISTS COURSE;
CREATE TABLE COURSE (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS FOOD_CATEGORY;
CREATE TABLE FOOD_CATEGORY (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS INGREDIENT;
CREATE TABLE INGREDIENT (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS QUANTITY;
CREATE TABLE QUANTITY (
id INT AUTO_INCREMENT PRIMARY KEY,
recipe_id INT NOT NULL,
ingredient_id INT NOT NULL,
ingredient_uom_id INT NOT NULL,
ingredient_quantity float NOT NULL
);

DROP TABLE IF EXISTS UNIT_OF_MEASUREMENT;
CREATE TABLE UNIT_OF_MEASUREMENT (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS RECIPE_STEPS;
CREATE TABLE RECIPE_STEPS (
id INT AUTO_INCREMENT PRIMARY KEY,
recipe_id INT NOT NULL,
step_number INT NOT NULL,
step_description TEXT NOT NULL
);

-- foreign keys

ALTER TABLE RECIPE
ADD FOREIGN KEY (course_id) REFERENCES COURSE(id);
ALTER TABLE RECIPE
ADD FOREIGN KEY (food_category_id) REFERENCES FOOD_CATEGORY(id);

ALTER TABLE QUANTITY
ADD FOREIGN KEY (recipe_id) REFERENCES RECIPE(id);
ALTER TABLE QUANTITY
ADD FOREIGN KEY (ingredient_id) REFERENCES INGREDIENT(id);
ALTER TABLE QUANTITY
ADD FOREIGN KEY (ingredient_uom_id) REFERENCES UNIT_OF_MEASUREMENT(id);

ALTER TABLE RECIPE_STEPS
ADD FOREIGN KEY (recipe_id) REFERENCES RECIPE(id);